[package]

name = "is_zero"
version = "0.0.1"
authors = ["Daniel Fagnan <dnfagnan@gmail.com>"]

[lib]
name = "is_zero"
crate-type = ["dylib"]


[dependencies.postgres_extension]
path = "../../"

[dependencies.postgres_extension_macros]
path = "../../macros"
